version: 1.0.9.{build}
max_jobs: 8
branches:
    only:
        - master
        - onemt/master
        - onemt/branches/koh

clone_depth: 50
clone_folder: c:\projects\llbc
install:
    - cmd: >-
        git submodule update --init --recursive
        
        echo vs2017 | call WinPreBuild.bat 0
        
        echo vs2019 | call WinPreBuild.bat 0
       
image: 
    - Visual Studio 2019

configuration: 
    - release32
    - release64

platform: 
    - x86
    - x64

for:
-
    matrix:
        exclude:
            - configuration: release32
              platform: x64

            - configuration: release64
              platform: x86

build:
    verbosity: normal
    project: build\vs2019\llbc_vs2019.sln

notifications:
    - provider: Email
      to:
          - 964855959@qq.com # Longwei Lai
          - snakeflutes@gmail.com # Reckful
      on_build_success: false
      on_build_failure: true
      on_build_status_changed: true
